Repository woowacourse-teams/2025-ah-madda, pull requests merged in 2025-09, with the labels that each got.

#649 [FE] 조직 이미지 크기 최대 10MB로 제한
  client/src/features/Organization/New/constants/errorMessages.ts
  client/src/features/Organization/New/constants/validationRules.ts
  client/src/features/Organization/New/utils/getOrgErrorMessage.ts
  client/src/features/Organization/New/utils/validationRules.ts
Labels: feat, fe

#645 [BE] SMTP 발송량 제한 초과 오류 해결
  server/src/main/java/com/ahmadda/infra/config/AsyncConfig.java
  server/src/main/java/com/ahmadda/infra/notification/mail/SmtpEmailNotifier.java
  server/src/main/resources/application.yml
  server/src/test/java/com/ahmadda/learning/AwsS3ImageUploaderTest.java
  server/src/test/java/com/ahmadda/learning/SlackAlarmTest.java
  server/src/test/java/com/ahmadda/learning/notification/FcmPushNotifierTest.java
  server/src/test/java/com/ahmadda/learning/notification/SmtpEmailNotifierTest.java
Labels: fix, be

#653 [BE] 포키 서비스 테스트 보완
  server/src/test/java/com/ahmadda/application/EventStatisticServiceTest.java
  server/src/test/java/com/ahmadda/application/PokeServiceTest.java
Labels: refactor, be

#655 [BE] JPA Nplus1 Detector 버전 마이그레이션 (3.0.0 → 3.1.0)
  server/build.gradle
  server/src/test/java/com/ahmadda/annotation/IntegrationTest.java
Labels: chore, be

#643 [BE] 요청 속도 제한 필터 구조 개선 및 책임 분리
  server/src/main/java/com/ahmadda/presentation/filter/SlidingWindowRateLimitFilter.java
  server/src/main/java/com/ahmadda/presentation/filter/ratelimit/RateLimitExceededHandler.java
  server/src/main/java/com/ahmadda/presentation/filter/ratelimit/SlidingWindowRateLimitFilter.java
  server/src/test/java/com/ahmadda/presentation/filter/ratelimit/RateLimitExceededHandlerTest.java
  server/src/test/java/com/ahmadda/presentation/filter/ratelimit/SlidingWindowRateLimitFilterTest.java
Labels: refactor, be

#669 [BE] 과거 이벤트 조회 api 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/OrganizationService.java
  server/src/main/java/com/ahmadda/domain/event/EventRepository.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
Labels: feat, be

#672 [BE] 포키 30분내에 보낼 수 있는 횟수 3번으로 제한
  server/src/main/java/com/ahmadda/domain/notification/Poke.java
  server/src/test/java/com/ahmadda/domain/notification/PokeTest.java
Labels: refactor, be

#660 [BE] Async 환경에서 임시 EAGER 설정 제거 및 em.merge 기반 영속화 처리
  server/src/main/java/com/ahmadda/application/listener/EventCreatedListener.java
  server/src/main/java/com/ahmadda/application/listener/EventReadListener.java
  server/src/main/java/com/ahmadda/application/scheduler/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/domain/event/Guest.java
  server/src/main/java/com/ahmadda/domain/organization/OrganizationMember.java
  server/src/main/java/com/ahmadda/infra/notification/mail/SmtpEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/config/MailConfig.java
  server/src/main/java/com/ahmadda/infra/notification/push/FcmPushNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/push/config/PushConfig.java
  server/src/test/java/com/ahmadda/application/listener/EventCreatedListenerTest.java
  server/src/test/java/com/ahmadda/application/listener/EventReadListenerTest.java
  server/src/test/java/com/ahmadda/application/scheduler/EventNotificationSchedulerTest.java
Labels: refactor, be

#670 [BE] 관리자의 조직 제거 기능 구현
  server/src/main/java/com/ahmadda/application/OrganizationService.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
Labels: feat, be

#689 [BE] 이미지 업로드 크기 설정
  .github/workflows/be-dev-deploy-closed-prs.yml
  server/src/main/resources/application.yml
Labels: feat, be

#728 [BE] 코드 레빗 설정
  .coderabbit.yaml
  docs/be-code-convention.md
Labels: chore, be

#712 [FE] 닉네임 수정 & 중복 검사를 위한 프로필 페이지
  client/src/api/mutations/useEditNickname.ts
  client/src/api/queries/profile.ts
  client/src/api/types/profile.ts
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Profile/components/ProfileAvatar.tsx
  client/src/features/Profile/components/ProfileForm.tsx
  client/src/features/Profile/hooks/useNicknameForm.ts
  client/src/features/Profile/hooks/useProfile.ts
  client/src/features/Profile/hooks/useProfileNavigation.ts
  client/src/features/Profile/pages/ProfilePage.tsx
  client/src/router/route.tsx
  client/src/shared/components/Avatar/Avatar.tsx
  client/src/shared/constants/index.ts
Labels: feat, fe

#726 [BE] Gmail 전송 실패 시 AWS SES 대체 발송 로직 구현
  server/build.gradle
  server/src/main/java/com/ahmadda/infra/notification/mail/FailoverEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/SmtpEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/config/MailConfig.java
  server/src/main/java/com/ahmadda/infra/notification/mail/consumer/MailCircuitBreakerEventConsumer.java
  server/src/main/java/com/ahmadda/infra/notification/mail/consumer/MailRetryEventConsumer.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application.yml
  server/src/test/java/com/ahmadda/learning/infra/notification/FailoverEmailNotifierTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/SmtpEmailNotifierTest.java
Labels: feat, be

#731 [BE] 이벤트 주최자들이 데이터베이스에 저장안되는 문제 해결
  server/src/main/java/com/ahmadda/domain/event/Event.java
  server/src/main/java/com/ahmadda/domain/organization/OrganizationMemberRepository.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
Labels: refactor, be

#738 [BE] 포키의 FCM 기반 push 알림을 비동기 방식으로 변경
  server/src/main/java/com/ahmadda/infra/notification/push/FcmPushNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/push/FcmRegistrationTokenRepository.java
Labels: refactor, be

#739 [BE] 다중 인스턴스 환경에서 스케줄러 중복 실행으로 인한 알림 중복 발송 문제 해결
  server/build.gradle
  server/src/main/java/com/ahmadda/application/scheduler/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/domain/event/Event.java
  server/src/main/java/com/ahmadda/infra/config/SchedulingConfig.java
  server/src/main/resources/db/migration/v202509161713__add_shedlock_table.sql
  server/src/test/java/com/ahmadda/application/scheduler/EventNotificationSchedulerTest.java
Labels: feat, be

#740 [BE] 학습테스트의 Transactional으로 인한 문제 해결
  server/src/test/java/com/ahmadda/annotation/LearningTest.java
  server/src/test/java/com/ahmadda/infra/notification/push/FcmPushErrorHandlerTest.java
  server/src/test/java/com/ahmadda/learning/infra/image/AwsS3OrganizationImageUploaderTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/FailoverEmailNotifierTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/FcmPushNotifierTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/SlackAlarmTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/SmtpEmailNotifierTest.java
Labels: fix, be

#746 [BE] shedlock flyway 파일명 불일치 문제 수정
  server/src/main/resources/db/migration/V202509161713__add_shedlock_table.sql
Labels: fix, be

#760 [FE] 스페이스원이 아닌 경우 스페이스 참여 링크로 유도
  client/src/features/Event/Detail/components/info/EventActionButton.tsx
  client/src/features/Event/Detail/components/info/EventHeader.tsx
  client/src/features/Event/Overview/components/PastEventList.tsx
  client/src/router/InviteRedirect.tsx
  client/src/router/route.tsx
  client/src/shared/components/Icon/assets/edit.tsx
  client/src/shared/components/Icon/assets/index.ts
Labels: feat, fe

#777 [FE] Footer 아이콘 위치 변경 및 main.js 캐싱 설정
  client/src/assets/icon/github.png
  client/src/shared/components/Footer/Footer.tsx
Labels: feat, fe

#776 [BE] 이벤트 생성시 특정 그룹에게만 리마인더 알림 보내도록 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/application/scheduler/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/domain/event/EventReminderGroup.java
  server/src/main/java/com/ahmadda/domain/event/EventReminderGroupRepository.java
  server/src/main/java/com/ahmadda/domain/organization/OrganizationMemberRepository.java
  server/src/main/resources/db/migration/V202509231941__add_event_reminder_group.sql
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/scheduler/EventNotificationSchedulerTest.java
Labels: feat, be

#765 [FE] 이벤트 상세 페이지에 관리 페이지 이동 버튼 추가
  client/src/features/Event/Detail/components/info/EventActionButton.tsx
  client/src/features/Event/Detail/components/info/EventHeader.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/components/EventCard/EventCard.tsx
  client/src/shared/components/Icon/assets/index.ts
  client/src/shared/components/Icon/assets/setting.tsx
Labels: feat, fe

#735 [FE] 이벤트 공동 주최자 지정 기능 구현 & 알림 보낼 그룹 지정 플로우 추가
  client/src/api/queries/organization.ts
  client/src/api/types/organizations.ts
  client/src/features/Event/New/components/CoHostSelectModal.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/constants/formFieldConfig.ts
  client/src/features/Event/New/hooks/useBasicEventForm.ts
  client/src/features/Event/types/Event.ts
  client/src/shared/components/Tabs/Tabs.styled.ts
  client/src/shared/components/Tabs/Tabs.tsx
Labels: feat, fe

#717 [FE] 이벤트 스페이스 관리자 추가 기능 구현
  client/src/api/mutations/useDeleteOrganization.ts
  client/src/api/mutations/useUpdateOrganizationMemberRoles.ts
  client/src/api/queries/organization.ts
  client/src/api/types/organizations.ts
  client/src/features/Event/Manage/components/GuestList.tsx
  client/src/features/Organization/New/components/OrganizationCreateForm.tsx
  client/src/features/Organization/New/components/OrganizationDeleteModal.tsx
Labels: feat, fe

#792 [FE] suspense fallback 적용, 코드 스플리팅 수정
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/My/components/Info.tsx
  client/src/features/Event/My/constants/index.ts
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/OrganizationInfo.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Profile/pages/ProfilePage.tsx
  client/src/router/route.tsx
  client/src/shared/components/Loading/Loading.stories.tsx
  client/src/shared/components/Loading/Loading.styled.ts
  client/src/shared/components/Loading/Loading.tsx
  client/src/shared/components/Loading/index.ts
Labels: feat

#793 [FE] 공동 주최자 모달의 영역 밖으로 구성원 리스트가 벗어나는 문제 해결
  client/src/features/Event/New/components/CoHostSelectModal.tsx
Labels: fix, fe

#796 [FE] release v3.1 프론트 배포
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/My/components/Info.tsx
  client/src/features/Event/My/constants/index.ts
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/New/components/CoHostSelectModal.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/OrganizationInfo.tsx
  client/src/features/Event/Overview/components/OverviewSkeletons.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Profile/pages/ProfilePage.tsx
  client/src/router/route.tsx
  client/src/shared/components/Loading/Loading.stories.tsx
  client/src/shared/components/Loading/Loading.styled.ts
  client/src/shared/components/Loading/Loading.tsx
  client/src/shared/components/Loading/index.ts
  client/src/shared/components/Skeleton/Skeleton.stories.tsx
  client/src/shared/components/Skeleton/Skeleton.styled.ts
  client/src/shared/components/Skeleton/Skeleton.tsx
  client/src/shared/components/Skeleton/index.ts
  client/src/shared/components/Tabs/Tabs.styled.ts
  client/src/shared/components/Tabs/Tabs.tsx
Labels: fe

#802 [FE] release v3 프론트 배포
  client/src/assets/font/PretendardVariable.core.woff2
  client/src/features/Event/New/components/CoHostSelectModal.tsx
Labels: fe
