Repository woowacourse-teams/2025-ah-madda, pull requests merged in 2025-07, with the labels that each got.

#15 [FE] 폴더 구조 세팅
  client/src/__test__/.gitkeep
  client/src/api/.gitkeep
  client/src/features/.gitkeep
  client/src/features/Home/components/.gitkeep
  client/src/features/Home/containers/.gitkeep
  client/src/features/Home/hooks/.gitkeep
  client/src/features/Home/pages/.gitkeep
  client/src/features/Home/types/.gitkeep
  client/src/features/Home/utils/.gitkeep
  client/src/router/.gitkeep
  client/src/shared/.gitkeep
  client/src/shared/components/Button/.gitkeep
  client/src/shared/hooks/.gitkeep
  client/src/shared/utils/.gitkeep
Labels: chore, fe

#46 [BE] Exception 초기 세팅
  server/src/main/java/com/ahmadda/application/.gitkeep
  server/src/main/java/com/ahmadda/application/exception/BusinessFlowViolatedException.java
  server/src/main/java/com/ahmadda/application/exception/NotFoundException.java
  server/src/main/java/com/ahmadda/domain/.gitkeep
  server/src/main/java/com/ahmadda/domain/exception/BusinessRuleViolatedException.java
  server/src/main/java/com/ahmadda/domain/exception/NullPropertyException.java
  server/src/main/java/com/ahmadda/presentation/.gitkeep
  server/src/main/java/com/ahmadda/presentation/exception/GlobalExceptionHandler.java
Labels: chore, be

#40 [FE] husky 세팅
  client/.husky/commit-msg
  client/.husky/pre-commit
  client/commitlint.config.cjs
  client/package.json
  client/pnpm-lock.yaml
Labels: chore, fe

#42 [FE] 공통 컴포넌트 템플릿 자동화 세팅
  client/_templates/components/shared/index.ejs.t
  client/_templates/components/shared/main.ejs.t
  client/_templates/components/shared/prompt.cjs
  client/_templates/components/shared/stories.ejs.t
  client/_templates/components/shared/styled.ejs.t
  client/_templates/init/repo/new-repo.ejs.t
  client/global.d.ts
  client/package.json
  client/pnpm-lock.yaml
Labels: chore, fe

#30 [FE] 스토리북과 슬랙 연동 webhook 설정
  .github/actions/pnpm-setup-node/action.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/preview-storybook.yml
  client/package.json
  client/pnpm-lock.yaml
  client/src/shared/components/Test/Test.stories.ts
  client/src/shared/components/Test/Test.styled.ts
  client/src/shared/components/Test/Test.tsx
  client/src/shared/components/Test/index.ts
Labels: chore, fe

#69 [FE] Card 컴포넌트, 스토리북 구현
  client/src/shared/components/Card/Card.stories.tsx
  client/src/shared/components/Card/Card.styled.ts
  client/src/shared/components/Card/Card.tsx
  client/src/shared/components/Card/index.ts
Labels: feat, fe

#61 [FE] 공통 Flex 컴포넌트 & 스토리북 구현
  client/src/shared/components/Flex/Flex.stories.tsx
  client/src/shared/components/Flex/Flex.styled.ts
  client/src/shared/components/Flex/Flex.tsx
  client/src/shared/components/Flex/index.ts
Labels: feat, fe

#76 [FE] Icon 컴포넌트, 스토리북 구현
  client/.storybook/main.ts
  client/babel.config.cjs
  client/global.d.ts
  client/package.json
  client/pnpm-lock.yaml
  client/src/shared/components/Icon/Icon.stories.tsx
  client/src/shared/components/Icon/Icon.tsx
  client/src/shared/components/Icon/IconGallery.mdx
  client/src/shared/components/Icon/assets/back.tsx
  client/src/shared/components/Icon/assets/calendar.tsx
  client/src/shared/components/Icon/assets/clock.tsx
  client/src/shared/components/Icon/assets/close.tsx
  client/src/shared/components/Icon/assets/delete.tsx
  client/src/shared/components/Icon/assets/index.ts
  client/src/shared/components/Icon/assets/location.tsx
  client/src/shared/components/Icon/assets/plus.tsx
  client/src/shared/components/Icon/assets/users.tsx
  client/src/shared/components/Icon/index.ts
  client/webpack.config.cjs
Labels: feat, fe

#83 [FE] IconButton 컴포넌트, 스토리북 구현
  client/src/shared/components/IconButton/IconButton.stories.tsx
  client/src/shared/components/IconButton/IconButton.styled.ts
  client/src/shared/components/IconButton/IconButton.tsx
  client/src/shared/components/IconButton/index.ts
Labels: feat, fe

#68 [FE] ProgressBar 컴포넌트, 스토리북 구현
  client/src/shared/components/ProgressBar/ProgressBar.stories.tsx
  client/src/shared/components/ProgressBar/ProgressBar.styled.ts
  client/src/shared/components/ProgressBar/ProgressBar.tsx
  client/src/shared/components/ProgressBar/index.ts
Labels: feat, fe

#80 [FE] Tabs 컴포넌트, 스토리북 구현
  client/global.d.ts
  client/src/shared/components/Tabs/Tabs.stories.tsx
  client/src/shared/components/Tabs/Tabs.styled.ts
  client/src/shared/components/Tabs/Tabs.tsx
  client/src/shared/components/Tabs/index.ts
Labels: feat, fe

#81 [FE] Input 컴포넌트, 스토리북 구현
  client/src/shared/components/Input/Input.stories.tsx
  client/src/shared/components/Input/Input.styled.ts
  client/src/shared/components/Input/Input.tsx
  client/src/shared/components/Input/index.ts
Labels: feat, fe

#90 [BE] 이벤트 생성 API 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/Organization.java
  server/src/main/java/com/ahmadda/domain/OrganizationMember.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/EventCreateResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/EventResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/OrganizationCreateResponse.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationMemberTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationTest.java
  server/src/test/java/com/ahmadda/domain/PeriodTest.java
Labels: feat, be

#110 [BE] 이벤트 상세 정보 조회 API 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/EventDetailResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/EventResponse.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
Labels: feat, be

#111 [FE] 패칭/서버 상태 관리 라이브러리 설정
  client/eslint.config.js
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/.gitkeep
  client/src/api/ClientQueryProvider.tsx
  client/src/api/fetcher.ts
  client/src/main.tsx
Labels: chore, fe

#117 [BE] 주최한 이벤트의 게스트 현황, 비게스트 조직원에게 이메일 전송의 인증/인가 검증 추가
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/exception/AccessDeniedException.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/exception/GlobalExceptionHandler.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: refactor, be

#118 [BE] 이벤트 생성시 폼과 함께 생성, 이벤트 참여시 폼 제출과 함께 참여 API 구현
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/AnswerCreateRequest.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/application/dto/EventParticipateRequest.java
  server/src/main/java/com/ahmadda/application/dto/QuestionCreateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/Guest.java
  server/src/main/java/com/ahmadda/domain/OrganizationMemberRepository.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
Labels: feat, be

#122 [BE] 자신의 회원/조직원 정보 조회 API 구현
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/MemberService.java
  server/src/main/java/com/ahmadda/application/OrganizationMemberService.java
  server/src/main/java/com/ahmadda/application/dto/LoginMember.java
  server/src/main/java/com/ahmadda/domain/OrganizationMemberRepository.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/LoginController.java
  server/src/main/java/com/ahmadda/presentation/MemberController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationMemberController.java
  server/src/main/java/com/ahmadda/presentation/dto/AccessTokenResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/MemberResponse.java
  server/src/main/java/com/ahmadda/presentation/resolver/MemberArgumentResolver.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/MemberServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberServiceTest.java
Labels: feat, be

#104 [FE] 이벤트 상세 정보 페이지 퍼블리싱
  client/src/features/Event/Detail/components/DescriptionCard.tsx
  client/src/features/Event/Detail/components/EventDetailContent.tsx
  client/src/features/Event/Detail/components/EventDetailTitle.tsx
  client/src/features/Event/Detail/components/LocationCard.tsx
  client/src/features/Event/Detail/components/ParticipantsCard.tsx
  client/src/features/Event/Detail/components/PreQuestionCard.tsx
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/Detail/components/TimeInfoCard.tsx
  client/src/features/Event/Detail/hooks/useEventDetail.ts
  client/src/features/Event/Detail/pages/EventDetail.tsx
  client/src/features/Event/Detail/types/index.ts
  client/src/shared/components/Card/Card.tsx
Labels: feat, fe

#97 [FE] MyEvent 페이지 UI 구현
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventSection.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/My/components/EventTabsList.tsx
  client/src/features/Event/My/components/MyEventHeader.tsx
  client/src/features/Event/My/constants/index.ts
  client/src/features/Event/My/containers/MyEventContainer.tsx
  client/src/features/Event/My/hooks/useEvents.ts
  client/src/features/Event/My/pages/MyEvent.tsx
  client/src/features/Event/My/types/index.ts
  client/src/shared/components/Tabs/Tabs.styled.ts
Labels: feat, fe

#128 [BE] 개발 환경용 CORS 설정 추가
  server/src/main/java/com/ahmadda/presentation/config/WebMvcConfig.java
  server/src/main/resources/application-dev.yml
Labels: feat, be

#125 [BE] 이벤트 생성 시 주최자 이름을 입력받도록 API 수정
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/Question.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/EventDetailResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/EventResponse.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationMemberTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationTest.java
Labels: feat, be

#126 [BE] 우아한코스 조직 제공하도록 임시 api들 구현
  server/src/main/java/com/ahmadda/application/LoginService.java
  server/src/main/java/com/ahmadda/application/OrganizationService.java
  server/src/main/java/com/ahmadda/domain/OrganizationMemberRepository.java
  server/src/main/java/com/ahmadda/domain/OrganizationRepository.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
Labels: feat, be

#99 [FE] 이벤트 관리 페이지 UI 구현
  client/src/features/EventManage/components/AlarmSection.tsx
  client/src/features/EventManage/components/EventInfoSection.tsx
  client/src/features/EventManage/components/GuestItem.tsx
  client/src/features/EventManage/components/GuestList.tsx
  client/src/features/EventManage/components/GuestManageSection.tsx
  client/src/features/EventManage/components/GuestModal.tsx
  client/src/features/EventManage/components/GuestViewSection.tsx
  client/src/features/EventManage/constants/index.ts
  client/src/features/EventManage/containers/EventManageContainer.tsx
  client/src/features/EventManage/hooks/useEventManage.ts
  client/src/features/EventManage/pages/EventManage.tsx
  client/src/features/EventManage/types/index.ts
  client/src/shared/components/Icon/assets/alarm.tsx
  client/src/shared/components/Icon/assets/index.ts
Labels: feat, fe

#136 [FE] Header position 변경
  client/src/shared/components/Header/Header.styled.ts
  client/src/shared/components/Header/Header.tsx
Labels: refactor, fe

#108 [FE] 이벤트 생성 페이지 퍼블리싱
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/pages/CreateEvent.tsx
  client/src/shared/components/Input/Input.styled.ts
  client/src/shared/components/Input/Input.tsx
Labels: feat, fe

#137 [FE] page router 설정
  client/src/features/Event/Detail/components/EventDetailContent.tsx
  client/src/features/Event/Detail/components/EventDetailTitle.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/GuestItem.tsx
  client/src/features/Event/Manage/components/GuestList.tsx
  client/src/features/Event/Manage/components/GuestManageSection.tsx
  client/src/features/Event/Manage/components/GuestViewSection.tsx
  client/src/features/Event/Manage/constants/index.ts
  client/src/features/Event/Manage/containers/EventManageContainer.tsx
  client/src/features/Event/Manage/hooks/useEventManage.ts
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/Manage/types/index.ts
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventSection.tsx
  client/src/features/Event/My/components/MyEventHeader.tsx
  client/src/features/Event/My/containers/MyEventContainer.tsx
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/EventCard.tsx
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/features/Event/Overview/components/OrganizationInfo.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/EventManage/components/GuestModal.tsx
  client/src/router/route.tsx
  client/src/shared/components/Header/Header.tsx
  client/src/shared/components/Icon/assets/alarm.tsx
Labels: feat, fe

#140 [FE] webpack dotenv 설정
  client/package.json
  client/pnpm-lock.yaml
  client/webpack.config.cjs
Labels: chore, fe

#153 [BE] CI 스크립트 작성
  .github/workflows/validation-opened-prs.yml
Labels: feat

#146 [FE] 이벤트 생성 페이지 질문 작성 폼 퍼블리싱
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/components/QuestionItem.tsx
Labels: feat, fe

#160 [FE] Home 페이지 구현
  client/global.d.ts
  client/src/assets/icon/ahmadda.webp
  client/src/assets/icon/point.webp
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Home/component/Description.tsx
  client/src/features/Home/component/Info.tsx
  client/src/features/Home/component/MessageCard.tsx
  client/src/features/Home/constants/messages.ts
  client/src/features/Home/page/HomePage.tsx
  client/src/router/route.tsx
  client/src/shared/components/Icon/assets/index.ts
  client/src/shared/components/Icon/assets/logo.tsx
  client/src/shared/components/Text/Text.styled.ts
  client/webpack.config.cjs
Labels: feat, fe

#162 [FE] My Event 페이지 api 연결
  client/src/api/queries/my.ts
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventSection.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/My/hooks/useEvents.ts
  client/src/features/Event/My/types/index.ts
  client/src/features/Event/types/Event.ts
Labels: feat, fe

#167 [FE] 프론트엔드 ci/cd 환경 설정
  .github/workflows/fe-cicd-closed-prs.yml
  client/package.json
  client/src/__test__/testing.test.tsx
  client/src/features/Event/Detail/components/DescriptionCard.tsx
  client/src/features/Event/Overview/components/EventCard.tsx
Labels: chore, fe

#170 [FE] 프론트 CD 관련 코드 삭제
  .github/workflows/fe-ci-closed-prs.yml
  .github/workflows/fe-cicd-closed-prs.yml
Labels: chore, fe

#163 [FE] 이벤트 생성 API 연결
  client/src/api/fetcher.ts
  client/src/api/queries/event.ts
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/components/QuestionItem.tsx
  client/src/features/Event/New/hooks/useAddEvent.ts
  client/src/features/Event/New/hooks/useEventForm.ts
  client/src/features/Event/New/utils/convertToISOString.ts
  client/src/features/Event/types/Event.ts
Labels: feat, fe

#164 [FE] 이벤트 관리 페이지 api 연결
  client/src/api/fetcher.ts
  client/src/api/mutations/useAddAlarm.ts
  client/src/api/queries/event.ts
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/GuestItem.tsx
  client/src/features/Event/Manage/components/GuestList.tsx
  client/src/features/Event/Manage/components/GuestManageSection.tsx
  client/src/features/Event/Manage/components/GuestViewSection.tsx
  client/src/features/Event/Manage/constants/index.ts
  client/src/features/Event/Manage/containers/EventManageContainer.tsx
  client/src/features/Event/Manage/hooks/useEventManage.ts
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/Manage/types/index.ts
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/utils/date.ts
  client/src/router/route.tsx
  client/src/shared/constants/index.ts
  client/src/shared/utils/localStorage.ts
  client/webpack.config.cjs
Labels: feat, fe

#173 [FE] cd를 위한 buildspec.yml 작성
  client/buildspec.yml
Labels: chore, fe

#177 [FE] build 스크립트 수정
  client/buildspec.yml
  client/src/__test__/testing.test.tsx
Labels: fix, fe

#190 [FE] 내가 주최한/참여한 이벤트 GET api url 변경
  client/src/api/queries/my.ts
Labels: feat, fe

#187 [FE] 이벤트 전체 조회 날짜 가까운순 정렬
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/features/Event/Overview/utils/groupEventsByDate.ts
Labels: fix, fe

#191 [FE] guest status API 연결, 모집중/모집전 Badge 추가
  client/src/api/mutations/useParticipateEvent.ts
  client/src/api/queries/event.ts
  client/src/api/types/event.ts
  client/src/features/Event/Detail/components/EventDetailContent.tsx
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Overview/components/EventCard.tsx
Labels: feat, fe

#197 [FE] 참여 이벤트 탭 내에서는 이벤트 상세 페이지로 이동
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventSection.tsx
  client/src/features/Event/My/components/EventTabs.tsx
Labels: fix, fe

#196 [BE] 이벤트에 대해 테스트 하지 않은 부분 테스트 코드 작성
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/MyEventResponse.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
Labels: test, be

#204 [BE] 워크플로 이름 명시 및 멀티 플랫폼 빌드 속도 개선
  .github/workflows/close-linked-issues.yml
  .github/workflows/dev-deploy-closed-prs.yml
  .github/workflows/validation-opened-prs.yml
Labels: refactor, be

#199 [BE] Jwt Token Provider에 대해 테스트 하지 않은 테스트 코드 추가
  server/src/main/java/com/ahmadda/application/LoginService.java
  server/src/main/java/com/ahmadda/application/dto/LoginMember.java
  server/src/main/java/com/ahmadda/infra/jwt/JwtTokenProvider.java
  server/src/main/java/com/ahmadda/infra/oauth/dto/MemberPayload.java
  server/src/main/java/com/ahmadda/presentation/resolver/MemberArgumentResolver.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
  server/src/test/java/com/ahmadda/application/MemberServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberServiceTest.java
  server/src/test/java/com/ahmadda/infra/jwt/JwtTokenProviderTest.java
Labels: test, be

#207 [BE] Swagger 초기 세팅
  server/build.gradle
  server/src/main/java/com/ahmadda/infra/mail/SmtpNotificationMailer.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/LoginController.java
  server/src/main/java/com/ahmadda/presentation/MemberController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationMemberController.java
  server/src/main/java/com/ahmadda/presentation/config/SwaggerConfig.java
  server/src/main/java/com/ahmadda/presentation/resolver/AuthMember.java
  server/src/main/resources/application.yml
Labels: feat, be

#220 [FE] node 버전 다운그레이드 및 절대 경로 문제 해결
  client/pnpm-lock.yaml
Labels: fix, fe

#221 [BE] 자신의 프로필 조회, 자신의 조직원 프로필 조회, 이벤트 게스트 조회,이벤트 알림 스웨거 세팅
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/MemberController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationMemberController.java
Labels: refactor, be

#222 [BE] Event 생성 요청시에 받고있는 이벤트 신청 시작시간 삭제
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
Labels: refactor, be

#229 [BE] 로그인 API 설명 스웨거 추가
  server/src/main/java/com/ahmadda/infra/oauth/GoogleOAuthProvider.java
  server/src/main/java/com/ahmadda/presentation/LoginController.java
Labels: refactor, be

#230 [BE] 이벤트 및 조직 도메인 API Swagger 문서화
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
Labels: refactor, be

#239 [FE] release 브랜치에서도 ci workflow가 실행되도록 설정
  .github/workflows/fe-ci-closed-prs.yml
Labels: chore, fe

#238 [FE] Color palette 설정
  .coderabbit.yaml
  client/.storybook/main.ts
  client/.storybook/preview.tsx
  client/src/main.tsx
  client/src/shared/components/Icon/IconGallery.mdx
  client/src/shared/styles/Color.mdx
  client/src/shared/styles/colors.ts
  client/src/shared/styles/emotion.d.ts
  client/src/shared/styles/theme.ts
Labels: feat, fe

#243 [FE] 링크 공유시 보여줄 meta 태그 추가
  client/index.html
  client/public/main.png
Labels: feat, fe

#253 [BE] 이벤트 게스트 조회, 비게스트 조회 주최자 유효성 제거
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
Labels: refactor, be

#255 [BE] 조직원을 선택해서 알람을 보내는 기능 구현
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/dto/NonGuestsNotificationRequest.java
  server/src/main/java/com/ahmadda/application/dto/SelectedOrganizationMembersNotificationRequest.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
Labels: feat, be

#257 [FE] Text 컴포넌트 디자인 시스템 적용
  client/src/__test__/testing.test.tsx
  client/src/features/Event/Detail/components/DescriptionCard.tsx
  client/src/features/Event/Detail/components/EventDetailTitle.tsx
  client/src/features/Event/Detail/components/LocationCard.tsx
  client/src/features/Event/Detail/components/ParticipantsCard.tsx
  client/src/features/Event/Detail/components/PreQuestionCard.tsx
  client/src/features/Event/Detail/components/TimeInfoCard.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/GuestItem.tsx
  client/src/features/Event/Manage/components/GuestList.tsx
  client/src/features/Event/Manage/components/GuestViewSection.tsx
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventSection.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/components/QuestionItem.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/EventCard.tsx
  client/src/features/Event/Overview/components/EventSection.tsx
  client/src/features/Event/Overview/components/OrganizationInfo.tsx
  client/src/features/Home/component/Info.tsx
  client/src/features/Home/component/MessageCard.tsx
  client/src/features/Home/component/NicknameModal.tsx
  client/src/shared/components/Text/Text.styled.ts
  client/src/shared/components/Text/Text.tsx
  client/src/shared/components/Text/Typography.mdx
Labels: refactor, fe

#267 [BE] 게스트 참여 가능 여부 반환 API 주최자는 참여 불가하게 반환하도록 수정
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: refactor, be

#271 [BE] 이벤트 생성 시 모든 조직원들에게 이벤트 알림을 보내도록 기능 구현
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/domain/EventNotification.java
  server/src/main/java/com/ahmadda/domain/NotificationMailer.java
  server/src/main/java/com/ahmadda/infra/mail/MockNotificationMailer.java
  server/src/main/java/com/ahmadda/infra/mail/SmtpNotificationMailer.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventNotificationTest.java
Labels: feat, be

#275 [BE] 이벤트 생성시 장소, 설명 null 가능하게 변경 및 이벤트 신청 마감 기간과 이벤트 시작 시간이 같아도 …
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/PeriodTest.java
Labels: refactor, be

#280 [BE] 주최자일 경우 게스트 여부 true로 변경
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: refactor, be

#273 [FE] 이벤트 생성 폼 유효성 검사 및 전반 수정
  client/src/api/queries/my.ts
  client/src/features/Event/Detail/components/ParticipantsCard.tsx
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/MaxCapacityModal.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/components/QuestionItem.tsx
  client/src/features/Event/New/constants/validation.ts
  client/src/features/Event/New/hooks/useEventForm.ts
  client/src/features/Event/New/hooks/useEventValidation.ts
  client/src/features/Event/New/utils/convertDatetimeLocalToKSTISOString.ts
  client/src/features/Event/New/utils/convertToISOString.ts
  client/src/features/Event/New/utils/validateEventForm.ts
  client/src/features/Event/Overview/components/EventCard.tsx
  client/src/features/Event/types/Event.ts
  client/src/shared/components/Input/Input.styled.ts
  client/src/shared/components/Input/Input.tsx
  client/src/shared/components/Modal/Modal.tsx
  client/src/shared/hooks/useLockScroll.ts
Labels: feat, fe

#284 [BE] Slack 프로퍼티 활성화 및 slack.yml import 추가
  server/src/main/java/com/ahmadda/infra/slack/config/SlackReminderConfig.java
  server/src/main/resources/application.yml
Labels: fix, be

#287 [FE] 수용인원 수정
  client/src/features/Event/My/components/EventCard.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/hooks/useEventForm.ts
  client/src/features/Event/Overview/components/EventCard.tsx
Labels: fe

#288 [BE] release v0.0.2 백앤드 배포
  server/build.gradle
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/LoginService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/application/dto/MemberCreateAlarmDto.java
  server/src/main/java/com/ahmadda/application/dto/NonGuestsNotificationRequest.java
  server/src/main/java/com/ahmadda/application/dto/SelectedOrganizationMembersNotificationRequest.java
  server/src/main/java/com/ahmadda/domain/Email.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventNotification.java
  server/src/main/java/com/ahmadda/domain/NotificationMailer.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/main/java/com/ahmadda/infra/mail/MockNotificationMailer.java
  server/src/main/java/com/ahmadda/infra/mail/SmtpNotificationMailer.java
  server/src/main/java/com/ahmadda/infra/mail/config/MailConfig.java
  server/src/main/java/com/ahmadda/infra/slack/AsyncSlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/MockProductionSlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/SlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/config/SlackAlarmProperties.java
  server/src/main/java/com/ahmadda/infra/slack/config/SlackReminderConfig.java
  server/src/main/java/com/ahmadda/infra/slack/dto/MemberCreationAlarmPayload.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/config/SwaggerConfig.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/mail/event-notification.html
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventNotificationTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/PeriodTest.java
  server/src/test/java/com/ahmadda/learning/EventNotificationTest.java
Labels: be

#260 [FE] Tabs 컴포넌트 디자인 변경
  client/src/features/Event/Detail/components/ParticipantsCard.tsx
  client/src/features/Event/My/components/EventTabsList.tsx
  client/src/features/Event/My/components/Info.tsx
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Home/component/Info.tsx
  client/src/shared/components/Tabs/Tabs.styled.ts
  client/src/shared/components/Tabs/Tabs.tsx
Labels: feat, fe

#268 [FE] 이벤트 상세 페이지 내에서도 Tab으로 신청 현황 볼 수 있게 설정
  client/src/features/Event/Detail/components/ApplicationsTab.tsx
  client/src/features/Event/Detail/components/EventDetailContent.tsx
  client/src/features/Event/Detail/components/LocationCard.tsx
  client/src/features/Event/Detail/containers/EventDetailContainer.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/components/GuestItem.tsx
  client/src/shared/components/Tabs/Tabs.styled.ts
Labels: refactor, fe

#299 [FE] 시간 분 단위까지 보여지도록 수정
  client/src/features/Event/Overview/utils/formatDateTime.ts
Labels: feat, fe

#302 [BE] 주최자 이벤트 수정 기능 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/dto/EventUpdateRequest.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/EventUpdateResponse.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/PeriodTest.java
Labels: feat, be
