Repository woowacourse-teams/2025-ah-madda, pull requests merged in 2025-08, with the labels that each got.

#319 [BE] 코드의 안전성을 높이고, 의도를 명확히 하기위한 리팩토링
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/LoginService.java
  server/src/main/java/com/ahmadda/application/dto/EventCreateRequest.java
  server/src/main/java/com/ahmadda/application/dto/EventUpdateRequest.java
  server/src/main/java/com/ahmadda/application/dto/MemberCreateAlarmDto.java
  server/src/main/java/com/ahmadda/application/dto/MemberCreateAlarmPayload.java
  server/src/main/java/com/ahmadda/domain/Email.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventEmailPayload.java
  server/src/main/java/com/ahmadda/domain/EventNotification.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/NotificationMailer.java
  server/src/main/java/com/ahmadda/infra/jwt/JwtProvider.java
  server/src/main/java/com/ahmadda/infra/jwt/config/JwtProperties.java
  server/src/main/java/com/ahmadda/infra/jwt/config/JwtTokenProperties.java
  server/src/main/java/com/ahmadda/infra/jwt/dto/JwtMemberPayload.java
  server/src/main/java/com/ahmadda/infra/mail/MockNotificationMailer.java
  server/src/main/java/com/ahmadda/infra/mail/SmtpNotificationMailer.java
  server/src/main/java/com/ahmadda/infra/oauth/config/GoogleOAuthProperties.java
  server/src/main/java/com/ahmadda/infra/oauth/dto/MemberPayload.java
  server/src/main/java/com/ahmadda/infra/slack/AsyncSlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/MockSlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/SlackReminder.java
  server/src/main/java/com/ahmadda/infra/slack/config/SlackAlarmProperties.java
  server/src/main/java/com/ahmadda/infra/slack/dto/MemberCreatAlarmRequestBody.java
  server/src/main/java/com/ahmadda/presentation/config/CorsProperties.java
  server/src/main/java/com/ahmadda/presentation/resolver/MemberArgumentResolver.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventNotificationTest.java
  server/src/test/java/com/ahmadda/infra/jwt/JwtProviderTest.java
  server/src/test/java/com/ahmadda/infra/jwt/JwtTokenProviderTest.java
  server/src/test/java/com/ahmadda/learning/EventNotificationTest.java
  server/src/test/java/com/ahmadda/learning/SlackReminderTest.java
Labels: refactor, be

#323 [BE] 주최자 이벤트 수정 기능 리팩토링
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/main/java/com/ahmadda/domain/exception/UnauthorizedOperationException.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/exception/GlobalExceptionHandler.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventNotificationTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationMemberTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationTest.java
  server/src/test/java/com/ahmadda/domain/PeriodTest.java
  server/src/test/java/com/ahmadda/learning/EventNotificationTest.java
Labels: refactor, be

#307 [BE] 이벤트 취소 기능 구현
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/Guest.java
  server/src/main/java/com/ahmadda/domain/GuestRepository.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: feat, be

#329 [BE] 이벤트 주최자 여부 API 기능 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
  server/src/main/java/com/ahmadda/presentation/dto/OrganizerStatusResponse.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: feat, be

#332 [BE] 주최자 여부 API 스웨거 명세 수정
  server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
Labels: refactor, be

#339 [BE] 초대코드 생성 API 구현
  server/src/main/java/com/ahmadda/application/OrganizationInviteCodeService.java
  server/src/main/java/com/ahmadda/domain/InviteCode.java
  server/src/main/java/com/ahmadda/domain/InviteCodeRepository.java
  server/src/main/java/com/ahmadda/infra/generator/Base62RandomCodeGenerator.java
  server/src/main/java/com/ahmadda/infra/generator/RandomCodeGenerator.java
  server/src/main/java/com/ahmadda/presentation/OrganizationInviteCodeController.java
  server/src/main/java/com/ahmadda/presentation/dto/InviteCodeCreateResponse.java
  server/src/test/java/com/ahmadda/application/OrganizationInviteCodeServiceTest.java
  server/src/test/java/com/ahmadda/domain/InviteCodeTest.java
Labels: feat, be

#317 [FE] Tabs 모바일에서 깨지는 현상 수정
  client/src/features/Event/My/components/EventTabs.tsx
Labels: fix, fe

#303 [FE] Button 컴포넌트 디자인시스템 적용
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/MaxCapacityModal.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/components/QuestionItem.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Home/component/Info.tsx
  client/src/features/Home/component/NicknameModal.tsx
  client/src/features/Home/page/HomePage.tsx
  client/src/shared/components/Button/Button.stories.tsx
  client/src/shared/components/Button/Button.styled.ts
  client/src/shared/components/Button/Button.tsx
Labels: refactor, fe

#330 [FE] ky -> fetch 마이그레이션 진행
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/auth.ts
  client/src/api/fetcher.ts
  client/src/api/mutations/useAddAlarm.ts
  client/src/api/mutations/useCreateProfile.ts
  client/src/api/mutations/useParticipateEvent.ts
  client/src/api/queries/event.ts
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/shared/components/Button/Button.tsx
Labels: refactor, fe

#334 [FE] Checkbox 컴포넌트, 스토리북
  client/src/shared/components/CheckBox/CheckBox.stories.tsx
  client/src/shared/components/CheckBox/CheckBox.tsx
  client/src/shared/components/CheckBox/index.ts
Labels: feat, fe

#361 [BE] Swagger CORS 문제 해결
  server/src/main/java/com/ahmadda/presentation/config/SwaggerConfig.java
  server/src/main/resources/application.yml
Labels: feat, be

#343 [FE] Badge 컴포넌트, 스토리북
  client/src/shared/components/Badge/Badge.stories.tsx
  client/src/shared/components/Badge/Badge.styled.ts
  client/src/shared/components/Badge/Badge.tsx
  client/src/shared/components/Badge/index.ts
Labels: feat, fe

#340 [FE] GA 연동 수정
  client/index.html
  client/src/main.tsx
  client/src/shared/lib/gtag.ts
Labels: fix, fe

#375 [BE] 간혈적으로 배포 자동화가 실패하는 오류 해결
  .github/workflows/dev-deploy-closed-prs.yml
  .github/workflows/prod-deploy-on-release.yml
Labels: fix, be

#337 [FE] 센트리 설정 & 슬랙 연동
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/fetcher.ts
  client/src/lib/analytics.ts
  client/src/lib/sentry.ts
  client/src/main.tsx
  client/src/shared/utils/apiErrorHandler.ts
  client/webpack.config.cjs
Labels: chore, fe

#372 [BE] 이벤트 조회수 통계 기능 구현
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/EventStatisticService.java
  server/src/main/java/com/ahmadda/application/OrganizationService.java
  server/src/main/java/com/ahmadda/application/event/EventCreated.java
  server/src/main/java/com/ahmadda/application/event/EventCreatedListener.java
  server/src/main/java/com/ahmadda/application/event/EventRead.java
  server/src/main/java/com/ahmadda/application/event/EventReadListener.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventOperationPeriod.java
  server/src/main/java/com/ahmadda/domain/EventStatistic.java
  server/src/main/java/com/ahmadda/domain/EventStatisticRepository.java
  server/src/main/java/com/ahmadda/domain/EventViewMetric.java
  server/src/main/java/com/ahmadda/domain/Organization.java
  server/src/main/java/com/ahmadda/domain/Period.java
  server/src/main/java/com/ahmadda/infra/jwt/JwtProvider.java
  server/src/main/java/com/ahmadda/presentation/EventStatisticController.java
  server/src/main/java/com/ahmadda/presentation/dto/EventViewMetricResponse.java
  server/src/main/java/com/ahmadda/presentation/resolver/MemberArgumentResolver.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/EventStatisticServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventOperationPeriodTest.java
  server/src/test/java/com/ahmadda/domain/EventStatisticTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationTest.java
Labels: feat, be

#394 [BE] 만료기한이 지났거나, 잘못된 형식의 jwt인 경우 예외 처리
  server/src/main/java/com/ahmadda/infra/jwt/JwtProvider.java
Labels: refactor, be

#385 [BE] OAuth를 통해 구글 프로필을 불러오고 Member에 이미지Uri 추가 기능 구현
  server/src/main/java/com/ahmadda/application/LoginService.java
  server/src/main/java/com/ahmadda/domain/Member.java
  server/src/main/java/com/ahmadda/infra/oauth/dto/OAuthUserInfoResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/MemberResponse.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationSchedulerTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/EventStatisticServiceTest.java
  server/src/test/java/com/ahmadda/application/FcmRegistrationTokenServiceTest.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
  server/src/test/java/com/ahmadda/application/MemberServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationInviteCodeServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberServiceTest.java
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventStatisticTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
  server/src/test/java/com/ahmadda/domain/InviteCodeTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationMemberTest.java
  server/src/test/java/com/ahmadda/domain/OrganizationTest.java
  server/src/test/java/com/ahmadda/learning/SlackAlarmTest.java
  server/src/test/java/com/ahmadda/learning/notification/FcmPushNotifierTest.java
  server/src/test/java/com/ahmadda/learning/notification/SmtpEmailNotifierTest.java
Labels: feat, be

#402 [BE] 이벤트 정원 초과 시 알람 미전송 처리 및 테스트 보완 by 머피
  server/src/main/java/com/ahmadda/application/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/test/java/com/ahmadda/application/EventNotificationSchedulerTest.java
  server/src/test/java/com/ahmadda/domain/EventTest.java
Labels: refactor, be

#396 [FE] 이벤트 통계 퍼블리싱, API 연결
  client/src/api/queries/event.ts
  client/src/api/types/event.ts
  client/src/features/Event/Manage/components/Chart.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/GuestManageSection.tsx
  client/src/features/Event/Manage/components/Statistics.tsx
  client/src/features/Event/Manage/hooks/useHoverIndex.ts
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/Manage/util/formatDate.ts
  client/src/shared/components/Icon/assets/chart.tsx
  client/src/shared/components/Icon/assets/index.ts
Labels: feat, fe

#390 [BE] 게스트 답변 조회 API 구현
  server/src/main/java/com/ahmadda/application/EventGuestService.java
  server/src/main/java/com/ahmadda/application/dto/GuestAnswerResponse.java
  server/src/main/java/com/ahmadda/domain/Guest.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
Labels: feat, be

#395 [FE] 비로그인 상태에 401 에러 해결 & 모든 401에러는 토큰지우고 리다이렉트
  client/src/api/fetcher.ts
  client/src/features/Home/component/Info.tsx
  client/src/shared/utils/tokenErrorHandler.ts
Labels: fix, fe

#410 [BE] log 볼륨 설정 prod에서 활성화 및 dev에서 제거
  .github/workflows/dev-deploy-closed-prs.yml
  .github/workflows/prod-deploy-on-release.yml
Labels: chore, be

#392 [FE] 템플릿 불러오는 기능 구현
  client/src/api/queries/event.ts
  client/src/api/types/event.ts
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/TemplateModal.tsx
  client/src/features/Event/New/hooks/useBasicEventForm.ts
  client/src/features/Event/New/hooks/useTemplateLoader.ts
  client/src/shared/hooks/useLockScroll.ts
Labels: feat, fe

#411 [BE] 이벤트 수정시에도 조회수에 반영되도록 수정
  .github/workflows/prod-deploy-on-release.yml
  server/src/main/java/com/ahmadda/application/EventCreatedListener.java
  server/src/main/java/com/ahmadda/application/EventReadListener.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/EventUpdateListener.java
  server/src/main/java/com/ahmadda/application/dto/EventCreated.java
  server/src/main/java/com/ahmadda/application/dto/EventRead.java
  server/src/main/java/com/ahmadda/application/dto/EventUpdated.java
  server/src/main/java/com/ahmadda/domain/EventStatistic.java
  server/src/main/java/com/ahmadda/presentation/EventStatisticController.java
  server/src/main/resources/logger/cloudwatch/info-threshold-appender.xml
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventStatisticTest.java
Labels: feat

#421 [FE] 로그인 하지 않은 경우 fcm 토큰 요청 보내지 않도록 수정
  client/src/shared/notification/useInitializeFCM.ts
Labels: fix, fe

#178 [FE] 이벤트 관리 페이지 내에 필요한 테스트 코드 작성
  client/package.json
  client/pnpm-lock.yaml
  client/src/__test__/EventManagePage.test.tsx
  client/src/__test__/MyEventPage.test.tsx
  client/src/__test__/createTestQueryClient.ts
  client/src/__test__/customRender.tsx
  client/src/__test__/mocks/event.ts
  client/src/__test__/useAddAlarm.test.tsx
  client/src/features/Event/Overview/components/EventCard.tsx
  client/vitest.config.ts
Labels: test, fe

#426 [FE] 20억명 -> 무제한으로 워딩 변경
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
Labels: fix, fe

#184 [FE] 날짜 파싱 유틸 함수 테스트 작성
  client/src/features/Event/Overview/utils/__test__/formatDateTime.test.ts
  client/src/features/Event/Overview/utils/formatDateTime.ts
Labels: test, fe

#430 [FE] 수용인원 Modal 디자인 변경, hook 분리
  client/src/features/Event/New/components/MaxCapacityModal.tsx
  client/src/features/Event/New/components/TemplateModal.tsx
  client/src/features/Event/New/hooks/useMaxCapacity.ts
Labels: feat, fe

#428 [FE] Mobile에서 조직 초대 복사가 안되는 문제 해결
  client/src/api/mutations/useCreateInviteCode.ts
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/shared/components/Button/Button.styled.ts
Labels: fix, fe

#435 [FE] 이벤트 수정 시, 새 이벤트로 생성되는 문제 해결
  client/src/features/Event/New/components/EventCreateForm.tsx
Labels: fix, fe

#453 [BE] Async 환경에서 JPA 삭제 시 트랜잭션 미전파로 인한 InvalidDataAccessApiUsageException 해결
  server/src/main/java/com/ahmadda/infra/notification/push/FcmRegistrationTokenRepository.java
Labels: fix, be

#455 [BE] 이벤트 조회수 관련 방어 로직 구현
  server/src/main/java/com/ahmadda/application/EventReadListener.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/EventUpdateListener.java
  server/src/main/java/com/ahmadda/application/dto/EventRead.java
  server/src/main/java/com/ahmadda/domain/EventStatistic.java
  server/src/test/java/com/ahmadda/application/EventCreatedListenerTest.java
  server/src/test/java/com/ahmadda/application/EventReadListenerTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/EventStatisticServiceTest.java
  server/src/test/java/com/ahmadda/application/EventUpdateListenerTest.java
  server/src/test/java/com/ahmadda/application/OrganizationMemberEventServiceTest.java
  server/src/test/java/com/ahmadda/domain/EventStatisticTest.java
Labels: refactor, be

#451 [FE] 잘못된 url 접근 시 에러 페이지 렌더링 테스트 작성
  client/src/__test__/ErrorPageRender.test.tsx
Labels: test, fe

#472 [BE] 이벤트 시작 시간 24시간 전 리마인드 기능 구현
  server/src/main/java/com/ahmadda/application/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/domain/EventRepository.java
  server/src/test/java/com/ahmadda/application/EventNotificationSchedulerTest.java
Labels: feat, be

#474 [BE] 메일 템플릿에 아맞다 로고 추가
  server/src/main/resources/templates/mail/event-notification.html
Labels: refactor, be

#185 [FE] 이벤트 상세 정보 및 생성 페이지 테스트 작성
  client/src/__test__/testing.test.tsx
  client/src/api/authQueries.ts
  client/src/features/Event/Detail/__test__/EventDetailPage.test.tsx
  client/src/features/Event/Detail/__test__/formatKoreanDateTime.test.ts
  client/src/features/Event/New/__test__/NewEventPage.test.tsx
  client/vitest.config.ts
Labels: test, fe

#480 [BE] 메일 템플릿 로고를 s3 이미지 url을 사용하도록 변경
  server/src/main/resources/templates/mail/event-notification.html
Labels: refactor, be

#487 [BE] 이벤트 알림 안받기 기능 구현
  server/src/main/java/com/ahmadda/application/EventNotificationOptOutService.java
  server/src/main/java/com/ahmadda/domain/EventNotificationOptOut.java
  server/src/main/java/com/ahmadda/domain/EventNotificationOptOutRepository.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationOptOutController.java
  server/src/test/java/com/ahmadda/application/EventNotificationOptOutServiceTest.java
  server/src/test/java/com/ahmadda/application/LoginServiceTest.java
Labels: feat, be

#476 [FE] 알림 history UI 퍼블리싱, api 연결
  client/src/api/mutations/useAddAlarm.ts
  client/src/api/queries/event.ts
  client/src/api/types/event.ts
  client/src/features/Event/Manage/components/AlarmHistoryModal.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/GuestManageSection.tsx
  client/src/features/Event/Manage/components/HistoryCard.tsx
  client/src/features/Event/Manage/containers/HistoryContainer.tsx
Labels: feat

#387 [FE] Toast 컴포넌트, 스토리북
  client/src/App.tsx
  client/src/shared/components/Toast/Toast.stories.tsx
  client/src/shared/components/Toast/Toast.styled.ts
  client/src/shared/components/Toast/Toast.tsx
  client/src/shared/components/Toast/ToastContext.tsx
  client/src/shared/components/Toast/index.ts
Labels: feat, fe

#495 [FE] 알림 api path 변경
  client/src/api/queries/event.ts
Labels: feat, fe

#471 [FE] Textarea 컴포넌트, 스토리북
  client/src/features/Event/New/__test__/NewEventPage.test.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/constants/errorMessages.ts
  client/src/shared/components/Textarea/Textarea.stories.tsx
  client/src/shared/components/Textarea/Textarea.styled.ts
  client/src/shared/components/Textarea/Textarea.tsx
  client/src/shared/components/Textarea/index.ts
Labels: feat, fe

#507 [REFACTOR] 콕찌르기 친절한 예외 메시지로 변경
  server/src/main/java/com/ahmadda/domain/Poke.java
  server/src/main/java/com/ahmadda/domain/PokeHistoryRepository.java
  server/src/main/java/com/ahmadda/presentation/PokeController.java
  server/src/test/java/com/ahmadda/application/PokeServiceTest.java
  server/src/test/java/com/ahmadda/domain/PokeTest.java
Labels: refactor

#500 [TEST] 이벤트 전체 조회 테스트 작성
  client/src/__test__/MyEventPage.test.tsx
  client/src/__test__/OverviewPage.test.tsx
  client/src/__test__/mocks/organization.ts
  client/src/__test__/testing.test.tsx
Labels: test

#502 [FE] Header 스토리북 에러 해결
  client/src/shared/components/Header/Header.stories.tsx
  client/src/shared/components/Header/Header.tsx
Labels: fix, fe

#504 [FE] 캘린더 & 타임피커 UI 구현
  client/src/shared/components/Calendar/Calendar.stories.tsx
  client/src/shared/components/Calendar/Calendar.styled.ts
  client/src/shared/components/Calendar/Calendar.tsx
  client/src/shared/components/Calendar/index.ts
  client/src/shared/components/TimePicker/TimePicker.stories.tsx
  client/src/shared/components/TimePicker/TimePicker.styled.ts
  client/src/shared/components/TimePicker/TimePicker.tsx
  client/src/shared/components/TimePicker/index.ts
  client/src/shared/hooks/useCalendar.ts
  client/src/shared/utils/calendar.ts
  client/src/shared/utils/timePicker.ts
Labels: feat, fe

#510 [BE] 수신 거부한 사용자에게 알림을 전송하지 않도록 처리
  server/src/main/java/com/ahmadda/application/EventNotificationOptOutService.java
  server/src/main/java/com/ahmadda/application/EventNotificationScheduler.java
  server/src/main/java/com/ahmadda/application/EventNotificationService.java
  server/src/main/java/com/ahmadda/application/EventService.java
  server/src/main/java/com/ahmadda/application/PokeService.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/GuestWithOptStatus.java
  server/src/main/java/com/ahmadda/domain/OrganizationMemberWithOptStatus.java
  server/src/main/java/com/ahmadda/presentation/EventGuestController.java
  server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
  server/src/main/java/com/ahmadda/presentation/PokeController.java
  server/src/main/java/com/ahmadda/presentation/dto/GuestWithOptOutResponse.java
  server/src/main/java/com/ahmadda/presentation/dto/OrganizationMemberWithOptOutResponse.java
  server/src/test/java/com/ahmadda/application/EventNotificationSchedulerTest.java
  server/src/test/java/com/ahmadda/application/EventNotificationServiceTest.java
  server/src/test/java/com/ahmadda/application/EventServiceTest.java
  server/src/test/java/com/ahmadda/application/PokeServiceTest.java
Labels: feat, be

#515 [BE] Async 실행 시 MDC 컨텍스트가 전파되도록 TaskDecorator 적용
  server/src/main/java/com/ahmadda/infra/config/AsyncConfig.java
  server/src/main/resources/logback-spring.xml
Labels: feat, be

#525 [BE] Micrometer를 활용한 로그 레벨별 이벤트 수 측정 및 CloudWatch 연동
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application-prod.yml
Labels: feat, be

#535 [BE] 내가 가입한 조직 조회 api 구현
  server/src/main/java/com/ahmadda/application/OrganizationService.java
  server/src/main/java/com/ahmadda/domain/OrganizationRepository.java
  server/src/main/java/com/ahmadda/presentation/OrganizationController.java
  server/src/main/java/com/ahmadda/presentation/dto/OrganizationMemberResponse.java
  server/src/main/resources/logback-spring.xml
  server/src/test/java/com/ahmadda/application/OrganizationServiceTest.java
Labels: feat, be

#529 [FE] 센트리 간소화 및 센트리에서 제공하는 에러바운더리 설정
  client/src/App.tsx
  client/src/api/fetcher.ts
  client/src/lib/sentry.ts
  client/src/shared/utils/apiErrorHandler.ts
Labels: fix, fe

#540 [FE] 점검중 문구 변경
  client/src/features/Home/component/Info.tsx
Labels: chore, fe

#485 [FE] 이벤트 폼 자동 저장 기능 구현
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/QuestionForm.tsx
  client/src/features/Event/New/hooks/useBasicEventForm.ts
  client/src/features/Event/New/hooks/useQuestionForm.ts
  client/src/shared/hooks/useAutoSessionSave.ts
  client/src/shared/utils/safeSessionStorage.ts
Labels: feat, fe

#497 [FE] 캘린더 및 TimePicker 구현
  client/src/features/Event/New/__test__/NewEventPage.test.tsx
  client/src/features/Event/New/components/DatePickerDropdown.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/containers/DatePickerContainer.tsx
  client/src/features/Event/New/hooks/useDateSelection.ts
  client/src/features/Event/New/hooks/useDropdownStates.ts
  client/src/features/Event/New/hooks/useRangeDatePicker.ts
  client/src/features/Event/New/hooks/useSingleDatePicker.ts
  client/src/features/Event/New/hooks/useTimeSelection.ts
  client/src/features/Event/New/types/time.ts
  client/src/features/Event/New/utils/date.ts
  client/src/features/Event/New/utils/time.ts
  client/src/shared/components/Calendar/Calendar.stories.tsx
  client/src/shared/components/Calendar/Calendar.styled.ts
  client/src/shared/components/Calendar/Calendar.tsx
  client/src/shared/components/Icon/assets/index.ts
  client/src/shared/components/Icon/assets/next.tsx
  client/src/shared/components/Input/Input.styled.ts
  client/src/shared/components/Input/Input.tsx
  client/src/shared/components/Text/Text.styled.ts
  client/src/shared/components/Text/Text.tsx
  client/src/shared/components/TimePicker/TimePicker.styled.ts
  client/src/shared/hooks/useCalendar.ts
  client/src/shared/hooks/useClickOutside.ts
Labels: feat, fe

#561 [FE] staging에서의 로그인 redirect 추가
  client/src/api/auth.ts
Labels: feat, fe

#555 [BE] 필수질문에 대한 답변이 빈 문자열 값으로 와도 예외 처리되게 변경
  server/src/main/java/com/ahmadda/domain/Guest.java
  server/src/test/java/com/ahmadda/domain/GuestTest.java
Labels: refactor, be

#566 [BE] 클라이언트 Staging 환경 대응을 위한 CORS 설정 변경
  server/src/main/resources/application-dev.yml
Labels: refactor, be

#571 [BE] soft delete 적용
  server/src/main/java/com/ahmadda/domain/Answer.java
  server/src/main/java/com/ahmadda/domain/BaseEntity.java
  server/src/main/java/com/ahmadda/domain/Event.java
  server/src/main/java/com/ahmadda/domain/EventNotificationOptOut.java
  server/src/main/java/com/ahmadda/domain/EventStatistic.java
  server/src/main/java/com/ahmadda/domain/EventTemplate.java
  server/src/main/java/com/ahmadda/domain/EventViewMetric.java
  server/src/main/java/com/ahmadda/domain/Guest.java
  server/src/main/java/com/ahmadda/domain/InviteCode.java
  server/src/main/java/com/ahmadda/domain/Member.java
  server/src/main/java/com/ahmadda/domain/Organization.java
  server/src/main/java/com/ahmadda/domain/OrganizationMember.java
  server/src/main/java/com/ahmadda/domain/PokeHistory.java
  server/src/main/java/com/ahmadda/domain/Question.java
  server/src/main/java/com/ahmadda/domain/ReminderHistory.java
  server/src/main/java/com/ahmadda/domain/ReminderRecipient.java
  server/src/main/resources/db/migration/V202508201232__add_deleted_at_column.sql
Labels: feat, be

#551 [FE] 이벤트 매니지 페이지 디자인 반영
  client/src/__test__/EventManagePage.test.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/Chart.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/GuestItem.tsx
  client/src/features/Event/Manage/components/GuestList.tsx
  client/src/features/Event/Manage/components/GuestManageSection.tsx
  client/src/features/Event/Manage/components/GuestViewSection.tsx
  client/src/features/Event/Manage/components/Statistics.tsx
  client/src/features/Event/Manage/constants/index.ts
  client/src/features/Event/Manage/containers/GuestItemContainer.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/Manage/utils/eventCapacity.ts
  client/src/features/Event/Manage/utils/formatDate.ts
  client/src/shared/components/CheckBox/CheckBox.tsx
Labels: feat, fe

#581 [FE] 기존 alert -> Toast로 변경
  client/src/__test__/EventManagePage.test.tsx
  client/src/__test__/customRender.tsx
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/Detail/components/guest/GuestList.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/features/Event/Manage/components/DeadlineModal.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/components/MaxCapacityModal.tsx
  client/src/features/Event/New/hooks/useMaxCapacity.ts
  client/src/features/Event/New/hooks/useQuestionForm.ts
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/features/Event/Overview/utils/copyInviteMessage.ts
  client/src/features/Home/component/Info.tsx
  client/src/features/Invite/hooks/useInviteOrganizationProcess.tsx
  client/src/features/Invite/hooks/useNickNameForm.tsx
  client/src/router/ProtectRoute.tsx
  client/src/shared/components/Toast/Toast.styled.ts
  client/src/shared/components/Toast/Toast.tsx
  client/src/shared/components/Toast/ToastContext.tsx
Labels: feat, fe

#593 [BE] http://local.ahmadda.com:5173 cors 허용
  server/src/main/resources/application-local.yml
Labels: feat, be

#574 [FE] iOS & pwa로 진입시 알림 권한 요청 설정
  client/src/features/Event/My/components/NotificationButton.tsx
  client/src/features/Home/components/AlarmModal.tsx
  client/src/features/Home/components/Description.tsx
  client/src/features/Home/components/GuideModal.tsx
  client/src/features/Home/components/Info.tsx
  client/src/features/Home/components/Information.tsx
  client/src/features/Home/components/MessageCard.tsx
  client/src/features/Home/page/HomePage.tsx
  client/src/shared/.gitkeep
  client/src/shared/notification/firebase.ts
  client/src/shared/notification/useInitializeFCM.ts
  client/src/shared/notification/useNotification.ts
  client/src/shared/utils/.gitkeep
  client/src/shared/utils/device.ts
Labels: feat, fe

#527 [FE] 이벤트 알림 수신 거부 설정 및 해제 API 연결
  client/src/__test__/EventDetailPage.test.tsx
  client/src/__test__/customRender.tsx
  client/src/api/mutations/useEventNotificationToggle.ts
  client/src/api/queries/event.ts
  client/src/features/Event/Detail/components/SubmitButtonCard.tsx
  client/src/features/Event/Detail/components/info/EventHeader.tsx
  client/src/features/Event/Manage/components/AlarmSection.tsx
  client/src/shared/components/Toast/ToastContext.tsx
Labels: feat, fe

#601 [BE] Sliding Window 기반 요청 속도 제한 필터 구현
  server/src/main/java/com/ahmadda/presentation/filter/SlidingWindowRateLimitFilter.java
Labels: feat, be

#579 [BE] 테스트 환경에서 N+1 Detector 설정 변경
  server/src/main/resources/logback-spring.xml
  server/src/test/java/com/ahmadda/annotation/IntegrationTest.java
  server/src/test/resources/application-test.yml
Labels: refactor, be

#603 [FE] 조직 생성 페이지 퍼블리싱 및 API 연결
  client/src/api/fetcher.ts
  client/src/api/mutations/useCreateOrganization.ts
  client/src/api/types/organizations.ts
  client/src/features/Invite/component/OrganizationInfo.tsx
  client/src/features/Organization/New/components/CreatorNicknameModal.tsx
  client/src/features/Organization/New/components/OrganizationCreateForm.tsx
  client/src/features/Organization/New/components/OrganizationImageInput.tsx
  client/src/features/Organization/New/constants/errorMessages.ts
  client/src/features/Organization/New/constants/validationRules.ts
  client/src/features/Organization/New/hooks/useCreateOrganizationProcess.ts
  client/src/features/Organization/New/hooks/useOrganizationForm.ts
  client/src/features/Organization/New/pages/NewOrganizationPage.tsx
  client/src/features/Organization/New/utils/getOrgErrorMessage.ts
  client/src/features/Organization/New/utils/validateOrganizationForm.ts
  client/src/features/Organization/New/utils/validationRules.ts
  client/src/features/Organization/New/utils/validators.ts
  client/src/router/route.tsx
  client/src/shared/components/Input/Input.styled.ts
Labels: feat, fe

#539 [FE] 조직 선택 페이지 퍼블리싱, API 연결 및 조직 플로우 변경
  client/src/__test__/OverviewPage.test.tsx
  client/src/api/queries/organization.ts
  client/src/api/types/organizations.ts
  client/src/features/Event/Overview/components/EventList.tsx
  client/src/features/Event/Overview/components/OrganizationInfo.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Event/types/Event.ts
  client/src/features/Home/components/Info.tsx
  client/src/features/Invite/hooks/useInviteOrganizationProcess.tsx
  client/src/features/Organization/Select/components/OrgCard.tsx
  client/src/features/Organization/Select/pages/SelectOrganizationPage.tsx
  client/src/features/Organization/types/Organization.ts
  client/src/router/route.tsx
Labels: feat, fe

#605 [FE] webpack 내 contenthash 추가
  client/webpack.common.cjs
  client/webpack.prod.cjs
Labels: chore, fe

#606 [FE] 조직 수정 API 연결
  client/src/api/mutations/useCreateOrganization.ts
  client/src/api/mutations/useUpdateOrganization.ts
  client/src/api/queries/organization.ts
  client/src/features/Home/components/Info.tsx
  client/src/features/Organization/New/components/OrganizationCreateForm.tsx
  client/src/features/Organization/New/components/OrganizationImageInput.tsx
  client/src/features/Organization/New/hooks/useOrganizationForm.ts
  client/src/features/Organization/New/utils/validateOrganizationForm.ts
  client/src/features/Organization/Select/pages/SelectOrganizationPage.tsx
  client/src/router/route.tsx
Labels: feat, fe

#608 [BE] SemVer에서 HeadVer로 변경
  .github/workflows/be-dev-deploy-closed-prs.yml
  .github/workflows/be-prod-deploy-hotfix.yml
  .github/workflows/be-prod-deploy-on-release.yml
  .github/workflows/be-prod-rollback-on-manual.yml
  .github/workflows/be-validation-opened-prs.yml
  .github/workflows/tag-headver-on-merged-release.yml
Labels: feat, be

#614 [FE] 모든 navigate 점검 및 수정
  client/src/__test__/MyEventPage.test.tsx
  client/src/__test__/OverviewPage.test.tsx
  client/src/__test__/customRender.tsx
  client/src/features/Error/pages/ErrorPage.tsx
  client/src/features/Event/Detail/components/info/EventHeader.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/My/components/EventTabs.tsx
  client/src/features/Event/My/components/Info.tsx
  client/src/features/Event/My/pages/MyEventPage.tsx
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/pages/NewEventPage.tsx
  client/src/features/Event/Overview/components/ActionButtons.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
  client/src/features/Event/components/EventCard/EventCard.tsx
  client/src/features/Home/components/Info.tsx
  client/src/features/Home/page/HomePage.tsx
  client/src/features/Invite/component/InviteModal.tsx
  client/src/features/Invite/hooks/useInviteOrganizationProcess.tsx
  client/src/features/Organization/New/components/OrganizationCreateForm.tsx
  client/src/features/Organization/New/pages/NewOrganizationPage.tsx
  client/src/features/Organization/Select/pages/SelectOrganizationPage.tsx
  client/src/main.tsx
  client/src/router/route.tsx
Labels: feat, fe

#627 [FE] api flicker 문제 해결
  client/public/firebase-messaging-sw.js
  client/src/__test__/customRender.tsx
  client/src/features/Event/Detail/pages/EventDetailPage.tsx
  client/src/features/Event/Overview/pages/OverviewPage.tsx
Labels: fix, fe

#631 [FE] OrganizationCreateForm 내 navigate문제
  client/src/features/Organization/New/components/OrganizationCreateForm.tsx
Labels: fix, fe

#623 [FE] 캘린더 및 시간 선택 기능 테스트
  client/src/__test__/DatePickerDropdown.test.tsx
  client/src/__test__/customRender.tsx
Labels: test, fe
