Repository woowacourse-teams/2025-ah-madda, pull requests merged in 2025-10, with the labels that each got.

#806 [FE] 날짜 포맷 유틸 통합 (dayOfWeekFormat / locale 옵션 추가)
  client/src/__test__/dateUtils.test.ts
  client/src/__test__/formatKoreanDateTime.test.ts
  client/src/features/Event/Detail/components/info/EventDetails.tsx
  client/src/features/Event/Detail/components/info/EventHeader.tsx
  client/src/features/Event/Detail/utils/formatKoreanDateTime.ts
  client/src/features/Event/Manage/components/Chart.tsx
  client/src/features/Event/Manage/components/EventInfoSection.tsx
  client/src/features/Event/Manage/components/HistoryCard.tsx
  client/src/features/Event/Manage/pages/EventManagePage.tsx
  client/src/features/Event/Manage/utils/formatDate.ts
  client/src/features/Event/My/utils/date.ts
  client/src/features/Event/New/components/EventCreateForm.tsx
  client/src/features/Event/New/utils/convertDatetimeLocalToKSTISOString.ts
  client/src/features/Event/New/utils/date.ts
  client/src/features/Event/Overview/utils/formatTime.ts
  client/src/features/Event/components/EventCard/EventCard.tsx
  client/src/features/Event/utils/__test__/formatDateTime.test.ts
  client/src/features/Event/utils/formatDateTime.ts
  client/src/features/Home/utils/sum.ts
  client/src/shared/utils/dateUtils.ts
Labels: refactor, fe

#817 [BE] 리마인더 메일 발송 로직의 트랜잭션 경계 개선
  server/src/main/java/com/ahmadda/domain/notification/EmailNotifier.java
  server/src/main/java/com/ahmadda/domain/notification/EventEmailPayload.java
  server/src/main/java/com/ahmadda/domain/notification/Reminder.java
  server/src/main/java/com/ahmadda/domain/notification/ReminderEmail.java
  server/src/main/java/com/ahmadda/infra/notification/mail/BccChunkingEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/FailoverEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/NoopEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/RetryableEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/SmtpEmailNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/mail/config/MailConfig.java
  server/src/test/java/com/ahmadda/domain/notification/ReminderTest.java
  server/src/test/java/com/ahmadda/infra/notification/mail/BccChunkingEmailNotifierTest.java
  server/src/test/java/com/ahmadda/infra/notification/mail/RetryableEmailNotifierTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/FailoverEmailNotifierTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/SmtpEmailNotifierTest.java
Labels: refactor, be

#819 [BE] 리마인더/포키 푸시 발송 로직의 트랜잭션 경계 개선
  server/src/main/java/com/ahmadda/domain/notification/Poke.java
  server/src/main/java/com/ahmadda/domain/notification/PushNotifier.java
  server/src/main/java/com/ahmadda/domain/notification/Reminder.java
  server/src/main/java/com/ahmadda/infra/notification/push/FcmPushErrorHandler.java
  server/src/main/java/com/ahmadda/infra/notification/push/FcmPushNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/push/NoopPushNotifier.java
  server/src/main/java/com/ahmadda/infra/notification/push/config/PushConfig.java
  server/src/test/java/com/ahmadda/domain/notification/PokeTest.java
  server/src/test/java/com/ahmadda/domain/notification/ReminderTest.java
  server/src/test/java/com/ahmadda/learning/infra/notification/FcmPushNotifierTest.java
Labels: refactor, be

#824 [FE] 이벤트 신청 종료일 항상 시작 시간에 동기화
  client/src/features/Event/New/components/EventCreateForm.tsx
Labels: feat, fe

#826 [FE] 이벤트 생성 및 수정 시 입력한 시간과 다르게 출력되는 문제 해결
  client/src/features/Event/New/components/EventCreateForm.tsx
Labels: fix, fe
